services:
  app:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - VERSION=custom
    ports:
      - 3000:3000
    environment:
      RUST_LOG: info