services:
  web:
    image: nginx
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./otn-prod-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/usr/share/nginx/ssl/:ro

  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      RUST_LOG: info
